<template>
  <VCard
    color="white"
    class="mb-4"
  >
    <VCardTitle>
      <div class="text-xs">
        <p class="category grey--text font-weight-light"> 
          Jumlah Layanan/Servis
        </p>
        <h3 class="title display-1 font-weight-light">
          10 / 30 
        </h3>
      </div>
      <VSpacer />
      <VIcon
        right
        color="red elevation-10"
        size="50">
        build
      </VIcon>
    </VCardTitle>
  </VCard>
</template>
